spring.application.name=ordenes-service
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# MongoDB
spring.mongodb.uri=mongodb://admin:admin@mongodb:27017/ordenes?authSource=admin
